name = "Tree explorer"
status = "Working on it"
tag = ["navigation", "quality of life"]
desc = "Allow user the ability to navigate the tree of a given commit"
lsp-ref = ["code action", "goto definition"]
